#!/bin/bash

# Visualize the full git history in a format of a graph.

# Borrowed from
# https://stackoverflow.com/questions/1838873/visualizing-branch-topology-in-git/11594406.

git log --graph --full-history --all --color \
        --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"
