#!/bin/bash

# Visualize the git history in a format of a graph.

function print_help () {
    echo "Usage: $(basename -- "$0") full|day"
    exit 1
}

if [ $# -eq 0 ] || [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    print_help
fi

case $1 in
    full)
        # Borrowed from
        # https://stackoverflow.com/questions/1838873/visualizing-branch-topology-in-git/11594406.
        git log --graph --full-history --all --color \
                --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s"
    ;;
    day)
        # Thanks to https://tylerneely.com/!
        git log --name-only --graph --all --since=1.day.ago
    ;;
    *)
        print_help
    ;;
esac
