#!/bin/bash

set -Eeuo pipefail

_cleanup_list_git() {
    # Please keep in mind that X is used because only ignored files should
    # be deleted. Files not yet added to git index might be valuable.
    git clean -nXd | sed 's/^/  /'
}

_cleanup_git() {
    # Double f is here to remove downloaded repositories. Single f isn't
    # enough.
    git clean -ffXd | sed 's/^/  /'
}

cleanup_list_git() {
    directory="$1"
    pushd "${directory}" > /dev/null
    if [ -d .git ]; then
        echo "git files under ${directory} for cleanup..."
        _cleanup_list_git
    else
        echo "  no git files under ${directory}..."
    fi
    popd > /dev/null
}

cleanup_git () {
    directory="$1"
    pushd "${directory}" > /dev/null
    if [ -d .git ]; then
        echo "Cleaning ignored git files under ${directory} ..."
        _cleanup_list_git
        _cleanup_git
        echo "Done."
    else
        echo "  no git files under ${directory}..."
    fi
    popd > /dev/null
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    cleanup_git "${PWD}"
fi
